Orgchart2/Models/JobTitle.cs
using System.Collections.Generic;

namespace Orgchart2.Models
{
    public class JobTitle
    {
        public int Id { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}

Orgchart2/Controllers/JobTitleController.cs
using System.Web.Mvc;
using Orgchart2.Infrastructure;
using Orgchart2.Models;

namespace Orgchart2.Controllers
{
    public class JobTitleController : Controller
    {
        private readonly IOrgChartRepository<JobTitle> _repository;

        public JobTitleController(IOrgChartRepository<JobTitle> repository)
        {
            _repository = repository;
        }

        public ActionResult Index()
        {
            SetTitle();
            ViewBag.Heading = "Manage Job Titles";

            return View(_repository.SelectAll());
        }

        public ActionResult Add()
        {
            SetTitle();
            ViewBag.Heading = "Add New Job Title";

            return View();
        }

        [HttpPost]
        public ActionResult Add(JobTitle newJobTitle)
        {
            if (!ModelState.IsValid)
                return View(newJobTitle);

            _repository.Add(newJobTitle);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            SetTitle();
            ViewBag.Heading = "Confirm Job Title Deletion";

            var jobTitle = _repository.Select(id);

            if (jobTitle == null)
                return HttpNotFound();

            return View(jobTitle);
        }

        [HttpPost]
        public ActionResult Delete(int id, string confirm)
        {
            var jobTitle = _repository.Select(id);

            if (jobTitle == null)
                return HttpNotFound();

            _repository.Delete(jobTitle.Id);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var jobTitle = _repository.Select(id);

            if (jobTitle == null)
                return HttpNotFound();

            SetTitle();
            ViewBag.Heading = string.Format("Edit Job Title \"{0}\"", jobTitle.Description);

            return View(jobTitle);
        }

        [HttpPost]
        public ActionResult Edit(JobTitle title)
        {
            if (!ModelState.IsValid)
                return View(title);

            _repository.Update(title);
            return RedirectToAction("Index");
        }

        private void SetTitle()
        {
            ViewBag.Title = "Manage Job Titles";
        }
    }
}

Orgchart2/Views/JobTitle/Add.cshtml
@model Orgchart2.Models.JobTitle

@using (Html.BeginForm("Add", "JobTitle", FormMethod.Post))
{
    @Html.TextBoxFor(_ => _.Description)
    <input type="submit" />
}

Orgchart2/Views/JobTitle/Delete.cshtml
@model Orgchart2.Models.JobTitle

<p>Are you sure you want to delete job title "@Html.Encode(Model.Description)"?</p>

<p>
@using (Html.BeginForm("Delete", "JobTitle", FormMethod.Post))
{
    @Html.HiddenFor(_ => _.Id)
    <input type="submit" name="Confirm" value="Yes"> @:|
    @Html.ActionLink("Cancel", "Index")
}
</p>

Orgchart2/Views/JobTitle/Edit.cshtml
@model Orgchart2.Models.JobTitle

@using (Html.BeginForm("Edit", "JobTitle", FormMethod.Post))
{
    <p>
        @Html.HiddenFor(_ => _.Id)
        @Html.TextBoxFor(_ => _.Description)
    </p>
    <p>
        <input type="submit"> |
        @Html.ActionLink("Cancel", "Index")
    </p>
}

Orgchart2/Views/JobTitle/Index.cshtml
@model List<Orgchart2.Models.JobTitle>

@Html.ActionLink("Add new", "Add")

<table>
    <thead>
        <tr>
            <th colspan="3">Job Titles</th>
        </tr>
    </thead>
    <tbody>
@{
    foreach (var title in Model)
    {
        <tr>
            <td>@title.Description</td>
            <td>@Html.ActionLink("Edit", "Edit", new { id = title.Id })</td>
            <td>@Html.ActionLink("Delete", "Delete", new { id = title.Id })</td>
        </tr>
    }
}
    </tbody>
</table>